### ISSUE TITLE
Datamodel Parser: Support constraints and indexes with names that have invalid characters in Javascript

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#1037]
This isssue is part of an [epic](https://github.com/prisma/prisma/issues/3193).

**Tasks**
* [x] add the `map` argument to the attributes
  * [x] to `@@unique` -> extend the struct `IndexDefinition`
  * [x] to `@@index` -> extend the struct `IndexDefinition`
  * [x] to `@@id` -> change to `Model.id_fields` to use `IndexDefinition` as well.
* [ ] validate the `name` argument  to match the regex `[A-Za-z][A-Za-z0-9]*`
  * [x] in `@@unique`
  * [ ] in `@@index`
  * [x] in `@@id`

**Comment by mavilein** [comment]
The changes for `@@id` are probably a bit tricky. We should chat before this part is started.

**Comment by do4gr** [comment]
@@index is not taking a name argument since its not relevant to the client. Apart from that the work is done.
