### ISSUE TITLE
EPIC: Implement Errors Spec

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#128]
**Spec**: The relevant spec can be found [here](https://github.com/prisma/specs/tree/master/errors).

**Status**: This is currently **BLOCKED** by this [issue](https://github.com/prisma/prisma-engine/issues/109) which needs to be finished first to avoid unnecessary overhead.

**Description**: All engines must adhere to the errors spec. Our goal is to decouple error reporting from internal error handling. Therefore we will appraoch implementation like this:
* Create a new shared library called `user-facing-errors`. Inside this crate we will define all errors according to the specification. 
* Each engine and connector will provide conversion functions to turn an internal error into a user facing error that will be returned to the user.

**Draft**:
The shared library will define define errors from the spec 1:1 like this:
```rust
#[derive(Serialize)]
struct UserFacingError {
    code: String,
    message: String,
    meta: serde::Value
}

#[user_facing_error("P2008", "Failed to parse the query ${query_parsing_error} at ${query_position}")]
struct P2008 {
    query_parsing_error: String,
     query_position: String
}

/// The macro will create the following constructor function that takes care of the boilerplate:
pub fn new_p2008(error: InvalidCustomType) -> UserFacingError {
    UserFacingError {
        code: "P2008",
        message: format!("Failed to parse the query ${query_parsing_error} at ${query_position}", error.query_parsing_error, error.query_position),
        meta: serde::to_value(&error)
    }
}
```

Each engine and connector will then implement a function to enable error conversion:
```rust
fn map_error(error: ConnectorError) -> UserFacingError {
    match error {
        ConnectorError::FooBar(x) => new_p2008(P2008 { ... })
        ...
    }
}
```

## Links to actual Work Packages
* [x] [User Facing Errors Crate](https://github.com/prisma/prisma-engine/issues/133)
* [ ] [Datamodel Parser](https://github.com/prisma/prisma-engine/issues/129)
* [x] [Migration Engine](https://github.com/prisma/prisma-engine/issues/130)
* [x] [Query Engine](https://github.com/prisma/prisma-engine/issues/132)
* [x] [Introspection Engine](https://github.com/prisma/prisma-engine/issues/131)

**Comment by mavilein** [comment]
## Initial break down of Work Packages
* Datamodel Parser
  * implement conversion function from internal error to user facing error in core + connectors
* Migration Engine
  * implement conversion function from internal error to user facing error in core + connectors
* Query Engine
  * implement conversion function from internal error to user facing error in core + connectors
* Introspection Engine:
    * implement conversion function from internal error to user facing error in core + connectors

**Comment by PeterDraex** [comment]
I think this shouldn't be BLOCKED anymore, as the blocking issue has been resolved.

**Comment by janpio** [comment]
Correct @PeterDraex: Some work is now underway on some of the sub issues.

**Comment by yoshuawuyts** [comment]
Note from triage: sub-issues have been closed, we can close this as well.
