### ISSUE TITLE
[EPIC] MongoDB Engines General Availability

### ISSUE THREAD

**Issue by dpetrick** [prisma/prisma-engines#1593]
This epic is representing the collection of work items needed for integrating an MVP of MongoDB into major parts of the engines.

Client integration overview (anything migration CLI, Studio, TS/Go client) is not covered and will reside in separate issues, same goes for documentation efforts.

If something is not linked as a ticket, it means it wasn't done yet but will be in time.

Datamodel:
- [x] [Add MongoDB datasource to accepted datasources.](https://github.com/prisma/prisma-engines/issues/1594)
- [ ] https://github.com/prisma/prisma-engines/issues/1595

Introspection engine:
- [x] [Reject MongoDB introspection with a comprehensible error message.](https://github.com/prisma/prisma-engines/issues/1596)
- [ ] Implement introspection for JSON schema + non-schema cases (specifics to be determined).

Migration engine:
- [x] [Implement minimal migration engine connector for MongoDB](https://github.com/prisma/prisma-engines/issues/1602)
- [ ] Implement minimal constraint migrations (`@unique`, `@@unique`).
- [ ] Implement migration engine support (specifics to be determined).

Query engine:
- [x] [Set up connector skeleton.](https://github.com/prisma/prisma-engines/issues/1597)
- [x] [Implement basic write interface.](https://github.com/prisma/prisma-engines/issues/1598)
- [x] [Implement basic read interface.](https://github.com/prisma/prisma-engines/issues/1600)
- [x] [Create QE rust integration test harness.](https://github.com/prisma/prisma-engines/issues/1601)
- [x] https://github.com/prisma/prisma/issues/9014
- [ ] https://github.com/prisma/prisma-engines/issues/2063
- [x] Disable query raw API https://github.com/prisma/prisma-engines/pull/2087
- [x] https://github.com/prisma/prisma/issues/8266
- [ ] GroupBy isn't fully functional.
- [ ] Implement missing feature flags: 
    - [ ] `orderByRelations`
    - [ ] `orderByAggregateGroup`
    - [ ] `filterJson`
    - [ ] `selectRelationCount`

**Comment by matthewmueller** [comment]
FYI: Just disconnected this from the milestone and the board since it's cumbersome to keep two similar issues in sync.

**Comment by jkomyno** [comment]
Closing this, as MongoDB has already gone GA.
