### ISSUE TITLE
N-API Rust Epic

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma-engines#1627]
The initial version of the N-API lib already works great.
In order to integrate it properly in the TypeScript client, these are the things we still need:

- [x] Being able to provide the path to the datamodel file. Why? Because we need to be able to resolve the SQLite db relative to that
- [x] Batched request API
- [x] Expose `getConfig` (same as `dmmf`, which is already exposed)
- [x] Logging might need some rethinking
- [x] Panic handling should bubble up the message to JavaScript
