### ISSUE TITLE
EPIC: Multi field id criterion (Multi column PKs)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-engines#29]
**Spec**: The relevant part of the spec on the Prisma Schema Language can be found [here](https://github.com/prisma/specs/tree/master/schema#core-block-attributes).

**Description**: The Prisma Schema Language allows the user to define a combination of fields as the id criterion. It is an implementation detail of a connector how this is implemented.

**Example**:
The following example shows a `User` model where the combination of `firstName` and `lastName` is the id criterion.
```graphql
model User {
  firstName String
  lastName  String
  @@id([firstName, lastName])
}
```

**Affected Components**
- Datamodel Parser
- Migration Engine
- Query Engine
- Introspection Engine

## Links to actual Work Packages
* [x] [Datamodel Parser](https://github.com/prisma/prisma-engine/issues/66)
* [x] [Migration Engine](https://github.com/prisma/prisma-engine/issues/67)
* [x] https://github.com/prisma/prisma-engine/issues/60
* [x] [Query Engine](https://github.com/prisma/prisma-engine/issues/68)
* [x] [Introspection Engine](https://github.com/prisma/prisma-engine/issues/69)

**Comment by mavilein** [comment]
## Initial break down of Work Packages
* Datamodel Parser
  * extend `Model` data structure in `dml` module to store informations on multi field ids
  * implement new `DirectiveValidator` for `@@id`
  * test cases:
    * basic happy path
    * name arg must not be optional
    * the directive must not refer to undefined fields
    * a model must either have `@id` or `@@id`
* Migration Engine
  * core: implement new migration steps for indexes (diffing + applying)
  * sql connector:
    * calculation of sql schema
    * diffing of sql schemas
    * add SQL rendering to database step applier
* Query Engine
  * core:
    * adapt `Schema` so it can accept a combination fields as id criteria=on
    * adapt all places that expect an id to be a single `PrismaValue`
  * connector:
    * adapt all places that expect an id to be a single `PrismaValue`
* Introspection Engine:
    * core: no work required
    * connector:
        * verify that the `sql-schema-describer` can handle compound ids
        * adapt Datamodel calculation so that compound ids are translated to `@@id` in a model

**Comment by mavilein** [comment]
## Open Questions
- [ ] the GraphQL protocol for the communication between photon client and query engine must be defined

**Comment by mavilein** [comment]
I asked for a spec for the Photon API in this [issue](https://github.com/prisma/specs/issues/171).
